apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "starcoin-pricereporter-ingress"
#  namespace: "default"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app: starcoin-pricereporter
spec:
  rules:
    - http:
        paths:
          - path: /main/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: "starcoin-pricereporter"
                port:
                  number: 80
          - path: /barnard/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: "starcoin-pricereporter-barnard"
                port:
                  number: 80
