starcoin:
  stc-price-reporter:
    # bixin-task-cron: 1/5 * * * * ?
    # coinex-task-cron: 1/5 * * * * ?
    # gateio-task-cron: 1/10 * * * * ?
    bixin-task-fixed-delay: 30000
    coinex-task-fixed-delay: 30000
    gateio-task-fixed-delay: 30000

  sender-address: "0x82e35b34096f32c42061717c06e44a59"
  sender-private-key: ${STARCOIN_SENDER_PRIVATE_KEY}
  price-oracle-type-module-address: "0x82e35b34096f32c42061717c06e44a59"


ethereum:
  http-service-url: https://mainnet.infura.io/v3/72637bfa15a940dcadcec25a6fe0fca1


spring:
  flyway:
    enabled: true # 启用或禁用 flyway，生产状态一般情况下应该是启用


logging:
  level:
    org:
      starcoin:
        stcpricereporter: INFO
    root: INFO