starcoin:
#  chain-id: 251 # barnard test network
#  rpc-url: https://barnard-seed.starcoin.org
  stc-price-reporter:
    # bixin-task-cron: 1/5 * * * * ?
    # coinex-task-cron: 1/5 * * * * ?
    # gateio-task-cron: 1/10 * * * * ?
    bixin-task-fixed-delay: 10000
    coinex-task-fixed-delay: 10000
    gateio-task-fixed-delay: 10000
#  sender-address: '0x07fa08a855753f0ff7292fdcbe871216'
#  sender-private-key: ${STARCOIN_SENDER_PRIVATE_KEY}

  starswap:
    get-token-to-usd-exchange-rate-url: https://swap-api.starswap.xyz/main/v1/getToUsdExchangeRate?t={tokenId}


spring:
  flyway:
    enabled: false # 启用或禁用 flyway

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          # auto: create # 开发阶段使用
          auto: update


logging:
  level:
    org:
      starcoin:
        stcpricereporter: DEBUG
    root: INFO
